### ISSUE TITLE
Page design of login

### ISSUE THREAD

**Issue by shresth2102001** [Incentive-Coders/Shared_Backpack_User_App#1]
- **Issue Description:** 

You have to design the login page of the user app

- **Issue Severity:** 

High

- **Environment Details:** 

You to make a new file in screen folder which is present in lib folder. 

- **Other information:** 

Color codes should in hex codes 010103 and  d48a6f  (check the logo first it should match it.)

**Comment by gurvinder-yadav** [comment]
please assign me this issue

**Comment by yasharth291** [comment]
assigning this to you @gurvinder-yadav
