### ISSUE TITLE
Design Page for Signup

### ISSUE THREAD

**Issue by yasharth291** [Incentive-Coders/Shared_Backpack_User_App#2]
- *Issue Description:* 

You have to design the Signup page of the user app

- *Issue Severity:* 

High

- *Environment Details:* 

You to make a new file in the screen folder which is present in the lib folder. 

- *Other information:* 

Color codes should in black and orange (check the logo first) it should match it.

**Comment by grimreaperLinux** [comment]
I would like to work on this issue.

**Comment by siddharthbhandari03** [comment]
I would like to work on this.

**Comment by yasharth291** [comment]
ok assigning it to you  @grimreaperLinux

**Comment by SaltronTheLegend** [comment]
Plz assign me this issue.

**Comment by yasharth291** [comment]
Sorry @SaltronTheLegend its already issues
