### ISSUE TITLE
Page design for homepage 

### ISSUE THREAD

**Issue by shresth2102001** [Incentive-Coders/Shared_Backpack_User_App#3]
- **Issue Description:** 

You have to design the home page of the user app

- **Issue Severity:** 

High

- **Environment Details:** 

You to make a new file in screen folder which is present in lib folder. 

- **Other information:** 

Color codes should in hex codes 010103 and  d48a6f  (check the logo first it should match it.)

**Comment by Amruth56** [comment]
I would like to work on this

**Comment by yasharth291** [comment]
sure @Amruth56  assigning it to you

**Comment by o0aman0o** [comment]
hello
