### ISSUE TITLE
Page design for profile page in user app

### ISSUE THREAD

**Issue by shresth2102001** [Incentive-Coders/Shared_Backpack_User_App#4]
- **Issue Description:** 

You have to design the profile page of the user app

- **Issue Severity:** 

High

- **Environment Details:** 

You to make a new file in screen folder which is present in lib folder. 

- **Other information:** 

Color codes should in hex codes 010103 and  d48a6f  (check the logo first it should match it.)

**Comment by AnkitHinge-007** [comment]
Could you please assign me to do this issue?

**Comment by yasharth291** [comment]
ok assigning it to you @AnkitHinge-007
