### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by shresth2102001** [Incentive-Coders/Shared_Backpack_User_App#5]
- **Issue Description:** 

You have to design the Navbar of the user app

- **Issue Severity:** 

High

- **Environment Details:** 

You to make a new file in screen folder which is present in lib folder. 

- **Other information:** 

Color codes should in hex codes 010103 and  d48a6f  (check the logo first it should match it.)

**Comment by Great-Scottt** [comment]
Hey..I want to work on it

**Comment by o0aman0o** [comment]
hi this is Aman...above comment is also mine but I want to continue with this id

**Comment by yasharth291** [comment]
@o0aman0o  what is the progress

**Comment by o0aman0o** [comment]
just now created the pull request. Made the following changes as discussed before.
